CREATE TABLE IF NOT EXISTS filters (
    id VARCHAR(255) PRIMARY KEY,
    schema_version VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    consumer_id VARCHAR(255),
    output_topic VARCHAR(255) NOT NULL,
    conditions TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    condition_logic VARCHAR(10) NOT NULL DEFAULT 'AND',
    status VARCHAR(50) NOT NULL DEFAULT 'pending_approval',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    deployed_at TIMESTAMP,
    deployment_error TEXT,
    flink_statement_ids TEXT,
    targets VARCHAR(10000),
    approved_for_flink BOOLEAN DEFAULT false,
    approved_for_spring BOOLEAN DEFAULT false,
    approved_for_flink_at TIMESTAMP,
    approved_for_flink_by VARCHAR(255),
    approved_for_spring_at TIMESTAMP,
    approved_for_spring_by VARCHAR(255),
    deployed_to_flink BOOLEAN DEFAULT false,
    deployed_to_flink_at TIMESTAMP,
    deployed_to_spring BOOLEAN DEFAULT false,
    deployed_to_spring_at TIMESTAMP,
    flink_deployment_error TEXT,
    spring_deployment_error TEXT
);

