#!/bin/bash
# Setup script for Testcontainers configuration on macOS
# This script helps configure ~/.testcontainers.properties with the correct Docker socket path

set -e

echo "Testcontainers Setup for macOS"
echo "=============================="
echo ""

# Detect Docker socket location
DOCKER_SOCKET=""
DOCKER_HOST=""

# Check for default Docker socket (Docker Desktop with default socket enabled)
if [ -S "/var/run/docker.sock" ]; then
    DOCKER_SOCKET="/var/run/docker.sock"
    DOCKER_HOST="unix:///var/run/docker.sock"
    echo "✓ Found Docker socket at /var/run/docker.sock (Docker Desktop default socket enabled)"
elif [ -S "$HOME/.docker/run/docker.sock" ]; then
    DOCKER_SOCKET="$HOME/.docker/run/docker.sock"
    DOCKER_HOST="unix://$HOME/.docker/run/docker.sock"
    echo "✓ Found Docker socket at $HOME/.docker/run/docker.sock (macOS Docker Desktop)"
else
    echo "✗ Docker socket not found at common locations"
    echo ""
    echo "Please ensure Docker Desktop is running."
    echo ""
    echo "Option 1: Enable default Docker socket in Docker Desktop"
    echo "  - Open Docker Desktop"
    echo "  - Go to Settings → Advanced"
    echo "  - Enable 'Enable default Docker socket'"
    echo "  - Click 'Apply & Restart'"
    echo ""
    echo "Option 2: Specify custom Docker socket path"
    read -p "Enter Docker socket path (or press Enter to skip): " CUSTOM_SOCKET
    if [ -n "$CUSTOM_SOCKET" ] && [ -S "$CUSTOM_SOCKET" ]; then
        DOCKER_SOCKET="$CUSTOM_SOCKET"
        DOCKER_HOST="unix://$CUSTOM_SOCKET"
    else
        echo "Invalid socket path or socket does not exist. Exiting."
        exit 1
    fi
fi

echo ""
echo "Docker socket: $DOCKER_SOCKET"
echo "Docker host: $DOCKER_HOST"
echo ""

# Create or update ~/.testcontainers.properties
TESTCONTAINERS_PROPS="$HOME/.testcontainers.properties"
BACKUP_FILE="${TESTCONTAINERS_PROPS}.backup.$(date +%Y%m%d_%H%M%S)"

if [ -f "$TESTCONTAINERS_PROPS" ]; then
    echo "Backing up existing configuration to $BACKUP_FILE"
    cp "$TESTCONTAINERS_PROPS" "$BACKUP_FILE"
fi

# Update or create properties file
if grep -q "docker.host" "$TESTCONTAINERS_PROPS" 2>/dev/null; then
    # Update existing docker.host
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^docker.host=.*|docker.host=$DOCKER_HOST|" "$TESTCONTAINERS_PROPS"
    else
        # Linux
        sed -i "s|^docker.host=.*|docker.host=$DOCKER_HOST|" "$TESTCONTAINERS_PROPS"
    fi
    echo "✓ Updated docker.host in $TESTCONTAINERS_PROPS"
else
    # Add docker.host
    echo "" >> "$TESTCONTAINERS_PROPS"
    echo "# Docker host configuration (auto-generated by setup-testcontainers.sh)" >> "$TESTCONTAINERS_PROPS"
    echo "docker.host=$DOCKER_HOST" >> "$TESTCONTAINERS_PROPS"
    echo "✓ Added docker.host to $TESTCONTAINERS_PROPS"
fi

echo ""
echo "Configuration complete!"
echo ""
echo "You can now run tests with:"
echo "  ./gradlew test"
echo ""
echo "Or use the helper script:"
echo "  ./run-tests-with-docker.sh"
echo ""
