#!/bin/bash
# Setup Aurora Connection for Docker Compose
# Gets Aurora endpoint from Terraform and updates environment

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$REPO_ROOT/terraform"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}Aurora Connection Setup${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# Check if Terraform outputs exist
if [ ! -d "$TERRAFORM_DIR" ]; then
    echo -e "${RED}✗ Terraform directory not found: $TERRAFORM_DIR${NC}"
    exit 1
fi

cd "$TERRAFORM_DIR"

# Check if Terraform has been applied
if ! terraform output aurora_endpoint &> /dev/null; then
    echo -e "${RED}✗ Aurora infrastructure not deployed${NC}"
    echo "  Run: cd terraform && ./scripts/deploy-aurora.sh"
    exit 1
fi

# Get Aurora connection details
echo -e "${BLUE}[1/3] Getting Aurora connection details...${NC}"

AURORA_ENDPOINT=$(terraform output -raw aurora_endpoint 2>/dev/null || echo "")
AURORA_R2DBC_URL=$(terraform output -raw aurora_r2dbc_connection_string 2>/dev/null || echo "")

if [ -z "$AURORA_ENDPOINT" ] || [ -z "$AURORA_R2DBC_URL" ]; then
    echo -e "${RED}✗ Could not get Aurora connection details${NC}"
    echo "  Ensure Terraform has been applied: terraform apply"
    exit 1
fi

echo -e "${GREEN}✓ Aurora endpoint: $AURORA_ENDPOINT${NC}"

# Get database credentials
echo ""
echo -e "${BLUE}[2/3] Database Credentials${NC}"

# Try to get from terraform.tfvars
if [ -f "terraform.tfvars" ]; then
    DB_USER=$(grep -E "^database_user\s*=" terraform.tfvars | cut -d'"' -f2 | head -1 || echo "postgres")
    DB_PASSWORD=$(grep -E "^database_password\s*=" terraform.tfvars | cut -d'"' -f2 | head -1 || echo "")
else
    DB_USER="postgres"
    DB_PASSWORD=""
fi

if [ -z "$DB_PASSWORD" ]; then
    echo -e "${YELLOW}⚠ Database password not found in terraform.tfvars${NC}"
    read -sp "Enter database password: " DB_PASSWORD
    echo ""
fi

# Create environment file
echo ""
echo -e "${BLUE}[3/3] Creating environment file...${NC}"

ENV_FILE="$SCRIPT_DIR/../.env.aurora"
cat > "$ENV_FILE" << EOF
# Aurora PostgreSQL Connection
# Generated by setup-aurora-connection.sh
# Source this file: source .env.aurora

export AURORA_R2DBC_URL="$AURORA_R2DBC_URL"
export AURORA_USERNAME="$DB_USER"
export AURORA_PASSWORD="$DB_PASSWORD"

# For Confluent Cloud CDC Connector
export DB_HOSTNAME="$AURORA_ENDPOINT"
export DB_PORT="5432"
export DB_USERNAME="$DB_USER"
export DB_PASSWORD="$DB_PASSWORD"
export DB_NAME="car_entities"

# Use Aurora instead of local PostgreSQL
export USE_AURORA="true"
EOF

echo -e "${GREEN}✓ Environment file created: $ENV_FILE${NC}"

# Display connection details
echo ""
echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}Connection Details${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""
echo -e "${BLUE}Aurora Endpoint:${NC} $AURORA_ENDPOINT"
echo -e "${BLUE}R2DBC URL:${NC} $AURORA_R2DBC_URL"
echo -e "${BLUE}Username:${NC} $DB_USER"
echo ""

# Test connection (optional)
echo -e "${BLUE}Testing connection...${NC}"
if command -v psql &> /dev/null; then
    if PGPASSWORD="$DB_PASSWORD" psql -h "$AURORA_ENDPOINT" -U "$DB_USER" -d car_entities -c "SELECT 1;" &> /dev/null; then
        echo -e "${GREEN}✓ Connection test successful${NC}"
    else
        echo -e "${YELLOW}⚠ Connection test failed (may need to allow your IP in security group)${NC}"
    fi
else
    echo -e "${YELLOW}⚠ psql not available, skipping connection test${NC}"
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo ""
echo "1. Source the environment file:"
echo -e "${GREEN}   source $ENV_FILE${NC}"
echo ""
echo "2. Restart the API with Aurora connection:"
echo -e "${GREEN}   cd cdc-streaming${NC}"
echo -e "${GREEN}   docker-compose -f docker-compose.k6-confluent.yml up -d producer-api-java-rest${NC}"
echo ""
echo "3. Deploy Confluent Cloud connector:"
echo -e "${GREEN}   source $ENV_FILE${NC}"
echo -e "${GREEN}   ./scripts/deploy-confluent-postgres-cdc-connector.sh${NC}"
echo ""
