-- Flink SQL Statements for Event Filtering and Routing (Confluent Cloud)
-- This file is AUTO-GENERATED from filters.yaml
-- DO NOT EDIT MANUALLY - Changes will be overwritten
-- Generated by: generate-flink-sql.py
-- Source: filters.yaml
-- Target: Confluent Cloud Flink
-- 
-- Example structures:
-- - Car entity: data/entities/car/car-large.json
-- - Loan created event: data/schemas/event/samples/loan-created-event.json
-- - Loan payment event: data/schemas/event/samples/loan-payment-submitted-event.json
--
-- DEPLOYMENT NOTE: Deploy statements in order:
-- 1. Source table (raw-business-events)
-- 2. Sink tables (filtered-*-events)
-- 3. INSERT statements (one per filter)

-- ============================================================================
-- Step 1: Create Source Table
-- ============================================================================
-- Source Table: Raw Business Events from Kafka (Debezium CDC format)
-- Note: Table name must match topic name exactly in Confluent Cloud
-- This table reads the raw Debezium output format
CREATE TABLE `raw-business-events` (
    `id` STRING,
    `car_id` STRING,
    `entity_type` STRING,
    `created_at` STRING,
    `updated_at` STRING,
    `data` STRING,
    `__op` STRING,
    `__table` STRING,
    `__ts_ms` BIGINT
) WITH (
    'connector' = 'confluent',
    'value.format' = 'json-registry',
    'scan.startup.mode' = 'earliest-offset'
);

-- ============================================================================
-- Step 2: Create Sink Tables
-- ============================================================================
-- Sink Table: Loan Created Events Filter
-- Filters LoanCreated events based on data/schemas/event/samples/loan-created-event.json
-- Note: Table name must match topic name exactly in Confluent Cloud
-- Solution 1C: Keep Debezium format (flat structure, no nested ROWs)
-- Note: Excluding __ts_ms to avoid Flink eventtime inference
CREATE TABLE `filtered-loan-events` (
    `id` STRING,
    `car_id` STRING,
    `entity_type` STRING,
    `created_at` STRING,
    `updated_at` STRING,
    `data` STRING,
    `__op` STRING,
    `__table` STRING
) WITH (
    'connector' = 'confluent',
    'value.format' = 'json-registry'
);

-- Sink Table: Loan Payment Events Filter
-- Filters LoanPaymentSubmitted events based on data/schemas/event/samples/loan-payment-submitted-event.json
-- Note: Table name must match topic name exactly in Confluent Cloud
-- Solution 1C: Keep Debezium format (flat structure, no nested ROWs)
-- Note: Excluding __ts_ms to avoid Flink eventtime inference
CREATE TABLE `filtered-loan-payment-events` (
    `id` STRING,
    `car_id` STRING,
    `entity_type` STRING,
    `created_at` STRING,
    `updated_at` STRING,
    `data` STRING,
    `__op` STRING,
    `__table` STRING
) WITH (
    'connector' = 'confluent',
    'value.format' = 'json-registry'
);

-- Sink Table: Service Events Filter
-- Note: Table name must match topic name exactly in Confluent Cloud
-- Solution 1C: Keep Debezium format (flat structure, no nested ROWs)
-- Note: Excluding __ts_ms to avoid Flink eventtime inference
CREATE TABLE `filtered-service-events` (
    `id` STRING,
    `car_id` STRING,
    `entity_type` STRING,
    `created_at` STRING,
    `updated_at` STRING,
    `data` STRING,
    `__op` STRING,
    `__table` STRING
) WITH (
    'connector' = 'confluent',
    'value.format' = 'json-registry'
);

-- Sink Table: Car Creation Filter
-- Note: Table name must match topic name exactly in Confluent Cloud
-- Solution 1C: Keep Debezium format (flat structure, no nested ROWs)
-- Note: Excluding __ts_ms to avoid Flink eventtime inference
CREATE TABLE `filtered-car-events` (
    `id` STRING,
    `car_id` STRING,
    `entity_type` STRING,
    `created_at` STRING,
    `updated_at` STRING,
    `data` STRING,
    `__op` STRING,
    `__table` STRING
) WITH (
    'connector' = 'confluent',
    'value.format' = 'json-registry'
);

-- ============================================================================
-- Step 3: Deploy INSERT Statements (one per filter)
-- ============================================================================
-- Deploy each INSERT statement separately as individual Flink statements
-- Each INSERT statement should be deployed as a separate statement

-- ============================================================================
-- INSERT Statement: Loan Created Events Filter
-- Statement Name: loan-created-filter-insert
-- Filters LoanCreated events where loans reference car entities. Based on loan-created-event.json example structure.
-- Solution 1C: Simple SELECT with filtering (no transformation)
-- ============================================================================
INSERT INTO `filtered-loan-events`
SELECT 
    `id`,
    `car_id`,
    `entity_type`,
    `created_at`,
    `updated_at`,
    `data`,
    `__op`,
    `__table`
FROM `raw-business-events`
WHERE (`entity_type` = 'Loan' AND `__op` = 'c')
;

-- ============================================================================
-- INSERT Statement: Loan Payment Events Filter
-- Statement Name: loan-payment-filter-insert
-- Filters LoanPaymentSubmitted events
-- Solution 1C: Simple SELECT with filtering (no transformation)
-- ============================================================================
INSERT INTO `filtered-loan-payment-events`
SELECT 
    `id`,
    `car_id`,
    `entity_type`,
    `created_at`,
    `updated_at`,
    `data`,
    `__op`,
    `__table`
FROM `raw-business-events`
WHERE (`entity_type` = 'LoanPayment' AND `__op` = 'c')
;

-- ============================================================================
-- INSERT Statement: Service Events Filter
-- Statement Name: service-events-filter-insert
-- Filters events related to car services (CarServiceDone)
-- Solution 1C: Simple SELECT with filtering (no transformation)
-- ============================================================================
INSERT INTO `filtered-service-events`
SELECT 
    `id`,
    `car_id`,
    `entity_type`,
    `created_at`,
    `updated_at`,
    `data`,
    `__op`,
    `__table`
FROM `raw-business-events`
WHERE `entity_type` = 'ServiceRecord' AND `__op` = 'c'
;

-- ============================================================================
-- INSERT Statement: Car Creation Filter
-- Statement Name: car-creation-filter-insert
-- Filters car creation events. Based on car-large.json example structure.
-- Solution 1C: Simple SELECT with filtering (no transformation)
-- ============================================================================
INSERT INTO `filtered-car-events`
SELECT 
    `id`,
    `car_id`,
    `entity_type`,
    `created_at`,
    `updated_at`,
    `data`,
    `__op`,
    `__table`
FROM `raw-business-events`
WHERE (`entity_type` = 'Car' AND `__op` = 'c')
;
